import { z } from "zod";
import { UserRole, PermissionAction, Resource } from "../rbac";

/**
 * Strict AI Capability Boundary
 * Grace AI is restricted exclusively to READ, DRAFT, and ACTION_PROPOSAL.
 * EXECUTE, RAW_SQL, DYNAMIC_RPC, and DYNAMIC_TABLE_ACCESS are strictly prohibited.
 */
export type AiCapability = "READ" | "DRAFT" | "ACTION_PROPOSAL";

/**
 * Data Sensitivity Classification
 */
export type SensitiveDataLevel =
  | "PUBLIC"
  | "INTERNAL"
  | "FINANCIAL"
  | "SENSITIVE_FINANCIAL";

/**
 * Tagged wrapper for Untrusted External Data (OCR, prompts, notes, descriptions)
 */
export interface UntrustedData<T = string> {
  readonly _isUntrusted: true;
  readonly source: "user_prompt" | "ocr_text" | "database_content" | "external_input";
  readonly rawValue: T;
}

export function markAsUntrusted<T>(value: T, source: UntrustedData["source"] = "external_input"): UntrustedData<T> {
  return Object.freeze({
    _isUntrusted: true,
    source,
    rawValue: value,
  });
}

/**
 * Explicit Tool Definition Contract
 */
export interface AiToolDefinition<TInput = any, TOutput = any> {
  readonly name: string;
  readonly description: string;
  readonly capability: AiCapability;
  readonly inputSchema: z.ZodType<TInput>;
  readonly outputSchema: z.ZodType<TOutput>;
  readonly requiredPermissions: ReadonlyArray<{
    readonly action: PermissionAction;
    readonly resource: Resource;
  }>;
  readonly sensitiveDataLevel: SensitiveDataLevel;
  readonly auditAction: string;
  readonly allowedRoles: ReadonlyArray<UserRole>;
  readonly requiresConfirmation: boolean;
  readonly tenantScoped: boolean;
}

/**
 * AI Action Proposal Contract (Generated by Grace AI for human confirmation)
 */
export type ActionProposalStatus = "pending_confirmation" | "confirmed" | "rejected" | "expired";

export interface ActionProposal {
  readonly id: string;
  readonly church_id: string;
  readonly proposed_by_user_id: string;
  readonly action_type: "post_transaction" | "fund_transfer" | "void_transaction";
  readonly tool_name: string;
  readonly summary: string;
  readonly parameters: Record<string, any>;
  readonly payload_hash: string;
  readonly sensitive_data_level: SensitiveDataLevel;
  readonly created_at: string;
  readonly expires_at: string;
  readonly status: ActionProposalStatus;
}
