/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppOfferingRouteImport } from './routes/_app.offering'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppFundsRouteImport } from './routes/_app.funds'
import { Route as AppExpenseRouteImport } from './routes/_app.expense'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferingRoute = AppOfferingRouteImport.update({
  id: '/offering',
  path: '/offering',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppFundsRoute = AppFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseRoute = AppExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/expense': typeof AppExpenseRoute
  '/funds': typeof AppFundsRoute
  '/income': typeof AppIncomeRoute
  '/members': typeof AppMembersRoute
  '/offering': typeof AppOfferingRoute
  '/projects': typeof AppProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/expense': typeof AppExpenseRoute
  '/funds': typeof AppFundsRoute
  '/income': typeof AppIncomeRoute
  '/members': typeof AppMembersRoute
  '/offering': typeof AppOfferingRoute
  '/projects': typeof AppProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expense': typeof AppExpenseRoute
  '/_app/funds': typeof AppFundsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/offering': typeof AppOfferingRoute
  '/_app/projects': typeof AppProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/dashboard'
    | '/expense'
    | '/funds'
    | '/income'
    | '/members'
    | '/offering'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/dashboard'
    | '/expense'
    | '/funds'
    | '/income'
    | '/members'
    | '/offering'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/budget'
    | '/_app/dashboard'
    | '/_app/expense'
    | '/_app/funds'
    | '/_app/income'
    | '/_app/members'
    | '/_app/offering'
    | '/_app/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offering': {
      id: '/_app/offering'
      path: '/offering'
      fullPath: '/offering'
      preLoaderRoute: typeof AppOfferingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funds': {
      id: '/_app/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof AppFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense': {
      id: '/_app/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof AppExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpenseRoute: typeof AppExpenseRoute
  AppFundsRoute: typeof AppFundsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppMembersRoute: typeof AppMembersRoute
  AppOfferingRoute: typeof AppOfferingRoute
  AppProjectsRoute: typeof AppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpenseRoute: AppExpenseRoute,
  AppFundsRoute: AppFundsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppMembersRoute: AppMembersRoute,
  AppOfferingRoute: AppOfferingRoute,
  AppProjectsRoute: AppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
